import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


function Logo() {
  return (
    <div className="flex items-center gap-2">
      {/* <span className="text-2xl font-extrabold tracking-tight text-red-600">true</span>
      <span className="text-gray-300">|</span>
      <span className="text-2xl font-semibold tracking-wide">
        KN
        <span className="inline-flex h-2 w-2 rounded-full bg-red-500 align-middle mx-1" />
        W
      </span> */}
      <Image
        src="/true-icon.svg"
        width={183}
        height={50}
      />

    </div>
  );
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <div className="outer-wrapper h-screen overflow-y-auto">
      <div className="mobile-wrapper">
       <div className="flex justify-center mt-4">  <Logo/></div>
        {/* <h1 className="text-black text-2xl flex justify-center pt-8">True Know</h1> */}
        <ul className="flex flex-rows justify-center pt-4 gap-8">
          <li>Menu</li>
          <li>Collection</li>
          <li>About</li>
          <li>Contact Us</li>
        </ul>
        { children }
      </div>
    </div>
      </body>
    </html>
  );
}
