import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


function Logo() {
  return (
    <div className="flex items-center gap-2">
      {/* <span className="text-2xl font-extrabold tracking-tight text-red-600">true</span>
      <span className="text-gray-300">|</span>
      <span className="text-2xl font-semibold tracking-wide">
        KN
        <span className="inline-flex h-2 w-2 rounded-full bg-red-500 align-middle mx-1" />
        W
      </span> */}
      <svg src="/true-icon.svg">
        
      </svg>

    </div>
  );
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <div className="outer-wrapper h-screen overflow-y-auto">
      <div className="mobile-wrapper">
       <div className="flex justify-center mt-4">  <Logo/></div>
        {/* <h1 className="text-black text-2xl flex justify-center pt-8">True Know</h1> */}
        <ul className="flex flex-rows justify-center pt-4 gap-8">
          <li>Menu</li>
          <li>Collection</li>
          <li>About</li>
          <li>Contact Us</li>
        </ul>
        {/* <div className="h-[200px] mt-4 overflow-x-auto whitespace-nowrap flex gap-4 px-4">
          {["/img1.jpg", "/img2.jpg", "/img3.jpg"].map((src, index) => (
            <div key={index}
            className="inline-block w-full h-full bg-gradient-to-r from-red-400 to-red-600 rounded-lg text-white flex items-center justify-center text-xl shrink-0">
              Slide {index}
              </div>

    //           <img
    //   key={index}
    //   src={src}
    //   alt={`Slide ${index}`}
    //   className="inline-block w-[300px] h-full object-cover rounded-lg shrink-0"
    // />
          ))}
        </div> */}
        
        { children }
      </div>
    </div>
      </body>
    </html>
  );
}
