import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import MenuBar from "@/components/MenuBar";
import ImageSlider from "@/components/ImagesSlider";
import AnimatedStatsComponent from "@/components/AnimatedStatsComponent";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


function Logo() {
  return (
    <div className="flex items-center gap-2 mt-5">
      <Image
        src="/true-icon.svg"
        width={183}
        height={50}
      />

    </div>
  );
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <div className="outer-wrapper h-screen overflow-y-auto">
      <div className="mobile-wrapper">
       <div className="flex justify-center mt-4">  <Logo/></div>
        <MenuBar/>
        {/* { children } */}
        <ImageSlider/>
        <div class="m-2"><AnimatedStatsComponent/></div>
        <div className="p-7 mt-[-20]">
      <button className="w-full max-w-sm mx-auto bg-[#ED282E] text-white font-medium px-6 py-3 rounded-full flex items-center justify-between group hover:bg-[#d1242a] transition-colors">
        <span className="flex-1 text-left">
          เริ่มต้น
        </span>
        <svg 
          width="20" 
          height="20" 
          viewBox="0 0 24 24" 
          fill="none" 
          className="ml-2 group-hover:translate-x-1 transition-transform"
        >
          <path 
            d="M9 18L15 12L9 6" 
            stroke="currentColor" 
            strokeWidth="2" 
            strokeLinecap="round" 
            strokeLinejoin="round"
          />
        </svg>
      </button>
    </div>
      </div>
    </div>
      </body>
    </html>
  );
}
