'use client';

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import MenuBar from "@/components/MenuBar";
import { usePathname } from "next/navigation";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


function Logo() {
  return (
    <div className="flex items-center gap-2 mt-8">
      <Link href="/"><Image
        src="/true-icon.svg"
        alt=""
        width={183}
        height={50}
      />
</Link>
    </div>
  );
}
export default function RootLayout({ children }) {
  const pathName = usePathname();

  if (pathName.startsWith('/login') || pathName.startsWith('/register')) {
    return (
      <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="outer-wrapper h-screen overflow-y-auto">
          <div className="mobile-wrapper">
             <div className="flex justify-center mt-4">  <Logo/></div>
        { children }
          </div>
        </div>
      
      </body>
    </html>
    )
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <div className="outer-wrapper h-screen overflow-y-auto">
      <div className="mobile-wrapper">
       <div className="flex justify-center mt-4">  <Logo/></div>
        <MenuBar/>
        { children }
        
      </div>
    </div>
      </body>
    </html>
  );
}
